### PR TITLE
german translation

### PR DESCRIPTION
**Pull request by uDEV2019**

### CODE REVIEW

**Comment by HO-COOH** [comment]
Thanks for your time and effort. There are several places other than this `resw` that needs to be localized. I will add a guide in the readme then notify you back

**Comment by uDEV2019** [comment]
@HO-COOH I've looked into some of the other files but didn't see translatable strings.
Is there a timeline for making the mentioned guide available?

**Comment by HO-COOH** [comment]
Allowing me some more time. Have been extremely busy at work lately.

**Comment by HO-COOH** [comment]
Okay, I refactored a little bit and added [translation directions](https://github.com/HO-COOH/FastCopy#translation). Please check it out and adjust your pull request. Thanks a lot for your contribution!

**Comment by uDEV2019** [comment]
@HO-COOH Thanks for clarification. I have to admit that I didn't explicitly look into the file for the shell extension.

**Comment by HO-COOH** [comment]
Oh I also updated a few places in the main project during the refactor. Please also update it accordingly

**Pull request merged**
